<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Diminisher</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Diminisher.Application\Diminisher.Application.csproj" />
      <ProjectReference Include="..\Diminisher.Infrastructure\Diminisher.Infrastructure.csproj" />
    </ItemGroup>

</Project>
